//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_reg_H
#define METASPRITE_font_reg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_reg_TILE_ORIGIN 0
#define font_reg_TILE_W 8
#define font_reg_TILE_H 8
#define font_reg_WIDTH 760
#define font_reg_HEIGHT 8
#define font_reg_TILE_COUNT 95

BANKREF_EXTERN(font_reg)

extern const uint8_t font_reg_tiles[1520];

#endif
